FROM node:14-alpine

COPY ./client /app
WORKDIR /app/client
RUN npm install
RUN npm install react-scripts -g
RUN npm install html-react-parser
RUN npm install react-router-dom 
RUN npm install axios
RUN npm run build
EXPOSE 3000
CMD ["npm", "start"]