FROM node:14-alpine

WORKDIR /app
COPY ./server/server.js .
COPY ./server/database.js .
COPY ./server/package.json .

RUN npm install
RUN npm install -g nodemon
RUN npm install express
RUN npm install mysql
RUN npm install cors
RUN npm install body-parser

EXPOSE 80
CMD ["nodemon", "server.js"]